name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          echo "${{ secrets.mlops }}"
          docker image build -t csahin2086/mlops-flaskapp:v1
          docker push csahin2086/mlops-flaskapp:v1
