name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
      echo "${{ secrets.mlops }}" | docker login -u 'csahin2086' --password-stdin
      docker image build -t csahin2086/mlops-flaskapp:v1
      docker push csahin2086/mlops-flaskapp:v1
